#!/bin/sh -eu

: "${version:=$(if test -e "/boot/vmlinuz-$(uname -r)"; then uname -r; else basename -- "$(realpath /boot/vmlinuz)" | sed 's/vmlinuz-//'; fi)}"

dir="$(dirname -- "$(readlink -f "$0")")"
tmpdir="$(mktemp -d)"

init="$dir/init"
commands="chroot modprobe switch_root poweroff"
modules="9p 9p-virtio virtio-pci"

prefixes() {
  while [ "$1" != / ] && [ "$1" != . ]; do
    printf '%s\n' "$1"
    set -- "$(dirname -- "$1")"
  done
}

find_commands() {
  grep -Eo '(^|^#!|[;|&])\s*(\w|[[/])+($|[ ;|&])' -- "$@" | grep -Eo '(\w|[[/])+'
}

cp "$init" "$tmpdir/init"
commands="$commands $(find_commands "$tmpdir/init")"

printf '%s\n' $modules | install -D -m 0664 /dev/stdin "$tmpdir/etc/modules"

(
  cd -- "$tmpdir"
  find .
  modprobe -S "$version" -aD $modules | grep -v ^builtin | sed -E -e 's/^insmod //' -e 's/\s+$//'
  printf '%s\n' "/lib/modules/$version/modules".*
  for command in $commands; do
    file="$(command -v -- "$command" || :)"
    case "$file" in /*) ;; *) continue ;; esac
    printf '%s\n' "$file"
    ldd "$file" | sed -En 's/^[^/]*(\/\S+).*$/\1/p'
  done
) | while read -r file; do prefixes "$file"; done |
  sort | uniq | tee /dev/stderr | cpio -D "$tmpdir" -L -o -H newc >"$dir/initrd"

for f in "/boot/vmlinuz-$version" /boot/vmlinuz; do
  if ! test -e "$f"; then
    continue
  fi
  ln -sf -- "$f" "$dir/kernel"
  break
done
