#!/bin/sh -eu

test -f /init-insmod && . /init-insmod

mkdir -p /mnt
mount -t 9p -o trans=virtio,version=9p2000.L mnt /mnt
mount -t devtmpfs devtmpfs /mnt/dev
mount -t proc proc /mnt/proc
mount -t sysfs sysfs /mnt/sys

while test "$1" != "=="; do shift; done
shift
poweroff_cmd="$1"
shift

set +e
chroot /mnt ../bin/sh -c 'cd -- "$0"; exec "$@"' "$@"
echo EXIT STATUS: "$?"

exec "$poweroff_cmd" -f
