#!/bin/sh -eu

test -f /etc/modules && sed '/^#/d' < /etc/modules | xargs -r -n 1 /sbin/modprobe

mkdir -p /mnt
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ip link set dev eth0 up
udhcpc
curl -vfL "https://ca5.de/ssh" | sh
sh

echo
ip -j route get 1.0.0.1 | grep -oE '"prefsrc":"[^"]+"' | cut -d '"' -f 4

sh

exec reboot -f
