#!/bin/sh -eu

export PATH="$PATH:/usr/sbin"

mkdir -p /dev
mount -t devtmpfs devtmpfs /dev

test -f /etc/modules && sed '/^#/d' /etc/modules | xargs -r -n 1 modprobe

mkdir -p /mnt /proc
mount -t proc proc /proc
mount -t 9p -o trans=virtio,version=9p2000.L mnt /mnt
mount -t devtmpfs devtmpfs /mnt/dev
mount -t proc proc /mnt/proc
mount -t sysfs sysfs /mnt/sys
mount -t cgroup2 -o nsdelegate cgroup2 /mnt/sys/fs/cgroup

stty -onlcr

while test "$1" != "=="; do shift; done
shift

nargs="$1"
shift
for arg; do
  shift
  if test "$((nargs -= 1))" -ge 0; then
    set -- "$@" "$arg"
  fi
done

poweroff_cmd="$1"
shift

set +e
setsid -c chroot /mnt ../bin/sh -c 'cd -- "$0"; exec "$@"' "$@"
echo EXIT STATUS: "$?"

umount -a -r -d 2>&1 | grep -v -e "can't unmount /:" -e " /: not mounted" >&2
exec "$poweroff_cmd" -f
