#!/bin/sh

: "${cmdline=quiet}"
: "${kernel:="$(dirname -- "$(realpath -- "$0")")/kernel"}"

ARGS="$(
  for arg; do shift && test "$arg" = "--" && break; done
  if test "$#" = "0"; then
    set -- "${SHELL:-sh}"
  fi
  case "$PWD $@" in
    *\"*) exit 2 ;;
  esac
  printf ' "%s"' "$PWD" "$@"
)"
if test "$ARGS" = ""; then exit 2; fi

i=0
for arg; do
  if test "$((i += 1))" = "1"; then set --; fi
  if test "$arg" = "--"; then break; fi
  set -- "$@" "$arg"
done

exec qemu-system-x86_64 -M q35 \
  -kernel "$kernel" -device virtio-rng-pci \
  -serial stdio -display none -vga none \
  -fsdev local,id=root,path=/,security_model=none,multidevs=remap \
  -device virtio-9p-pci,fsdev=root,mount_tag=/dev/root \
  -append "$cmdline rootfstype=9p rootflags=trans=virtio,version=9p2000.L init=/bin/sh -- -c "'"stty -onlcr; mount -t proc proc /proc; mount -t sysfs sysfs /sys; IFS=; cd -- $0; $@; busybox poweroff -f"'" $ARGS" \
  "$@"
